sudo: false
language: python

python: 
  - 3.5

install:
  - pip install colored --upgrade
  - pip install python-coveralls
  - pip install codecov
script:
  coverage run -m unittest
after_success:
  - coverall
  - codecov
